import Collections from "../components/collections";
import Head from "next/head";
import Hero from "../components/hero";
import Image from "next/image";
import Navbar from "../components/navbar";
import Nft from "../components/nft";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div className="">
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>

			<Navbar />

			<Hero />

			<div className="">
				<h2>Curated Drops</h2>
				<div className="flex items-center justify-evenly">
					<Collections />
					<Collections />
					<Collections />
					<Collections />
				</div>
			</div>
			<div className="">
				<h2>Curated Collections</h2>
				<div className="flex flex-col items-center">
					<Nft />
					<Nft />
				</div>
			</div>

			<footer className=""></footer>
		</div>
	);
}
