import Collections from "../components/collections";
import Head from "next/head";
import Hero from "../components/hero";
import Image from "next/image";
import Navbar from "../components/navbar";
import Nft from "../components/nft";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div className="container m-auto">
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>

			<Navbar />

			<Hero />

			<div className="py-20">
				<h2 className="font-[Helvetica] text-xl">Curated Drops</h2>
				<div className="flex items-center justify-evenly">
					<Collections />
					<Collections />
					<Collections />
					<Collections />
				</div>
			</div>
			<div className="">
				<h2 className="font-[Helvetica] text-xl">
					Curated Collections
				</h2>
				<div className="bg-gradient-to-r from-sky-400 to-cyan-300 rounded-2xl">
					<Nft />
				</div>
			</div>
			<footer className="text-center py-5">
				MetaForge @ ETH India 2022
			</footer>
		</div>
	);
}
